### ISSUE TITLE
paigaldaja_meta.json not created

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer-rust#16]
The file is not created, regardless of whether the folder path is default or customized.
Doesn't seem to negatively affect its function, but considering what we discussed, this seems unintended anyway.

**Comment by vgskye** [comment]
CNR and such a thing shouldn't be able to happen, can you confirm again that `paigaldaja_meta.json` is not created at the profile directory?

**Comment by Madis0** [comment]
1. Downloaded the latest compiled build (ac1a6cec3c6cf213dc4a99ab231c5c645ddec98a) for Windows
2. Dragged the exe from zip to desktop
3. Ran it and installed 5.8.1, closed the installer
4. Tested the installed version
5. No file is created on my desktop

**Comment by vgskye** [comment]
the file is created in profile directory(ex, .minecraft) so

**Comment by Madis0** [comment]
Tested, indeed the file is there. At some point I remember seeing the file next to the installer, but I guess that was changed (good).
