### ISSUE TITLE
Deafult size is way too big

### ISSUE THREAD

**Issue by TheBossMagnus** [Fabulously-Optimized/vanilla-installer-rust#18]
Something like this might be more reasonable ![image](https://github.com/Fabulously-Optimized/vanilla-installer-rust/assets/92474350/bbfdca10-3f46-41d8-a104-4c41b8310d9f)

**Comment by vgskye** [comment]
I'm personally more partial to the more margin-y default size of right now, but I guess it's got a lot more wasted space
