### ISSUE TITLE
os error 3

### ISSUE THREAD

**Issue by Julienraptor01** [Fabulously-Optimized/vanilla-installer-rust#20]
Right after it has downloaded the mods, RPs and config
used the completly default install
Vanilla Launcher not installed and no minecraft dir present
![image](https://github.com/Fabulously-Optimized/vanilla-installer-rust/assets/49841713/1f7eb045-f9d1-4872-b47d-21a52430a326)

**Comment by vgskye** [comment]
duplicate of #17, I'd say
