### ISSUE TITLE
[Feature Request]: Make the icon smaller and maybe rounded

### ISSUE THREAD

**Issue by stantios** [Fabulously-Optimized/vanilla-installer-rust#22]
Description: I want the icon to be a smaller as the icon on macOS looks out of the ordinary and kinda looks out of place compared to other macOS icons as you can see in the screenshot. What I am suggesting is to make the icon smaller and maybe make it rounded if possible.

Screenshot:
![image](https://github.com/Fabulously-Optimized/vanilla-installer-rust/assets/98621617/c5c7908a-482a-422d-a518-8fa3d2a54898)

**Comment by vgskye** [comment]
currently looking at Apple's guidelines for what I should do, please stand by
