### ISSUE TITLE
Consider signing

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer-rust#29]
Maybe it is worth it to use this, have to consider
https://about.signpath.io/product/open-source
Ideally it'd support all OSes then, not just Windows

**Comment by vgskye** [comment]
Linux... doesn't have signing in the slightest and I don't think signpath provides macOS, you need the 99$/yr apple developer program for that I think

**Comment by Madis0** [comment]
There's also https://www.sigstore.dev/, which is potentially better because of big names backing it up ([some previous attempts did become paid](https://stackoverflow.com/questions/1177552/code-signing-certificate-for-open-source-projects), presumably due to lack of funding).

**Comment by vgskye** [comment]
I don't think sigstore is recognized by any real entity as a code signing cert?

**Comment by Madis0** [comment]
In that case, I guess sigstore is for code signing (which we don't necessarily need for this project) while SignPath is for binary signing.

**Comment by vgskye** [comment]
I think sigstore is more for docker containers and such and making sure the software wasn't tampered with on the way through rather than "can this be reasonably considered virus-free"

**Comment by vgskye** [comment]
Fabulously-Optimized/fabulously-optimized#849 needs to be merged and verification integrated in here to meet Signpath Foundation reqs

**Comment by Madis0** [comment]
Need to fulfill these criteria as well https://github.com/SignPath/Website-old/blob/v2/src/drafts/oss_policy.md
