### ISSUE TITLE
Folder path selector

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer-rust#3]
Not everyone may have the game in the default folder

**Comment by vgskye** [comment]
so, I cannot find an option in the Minecraft launcher to change the storage folder?

**Comment by Madis0** [comment]
"Game directory" in the individual installation settings
![image](https://github.com/Fabulously-Optimized/vanilla-installer-rust/assets/8611110/f7c4af50-1dc6-484b-b879-71071939c85f)

**Comment by vgskye** [comment]
ah, that? how should it interact with the profile isolation option?

**Comment by Madis0** [comment]
Perhaps the profiles could be inside that folder?
So something like `~/.minecraft/FOversions/4.10.4`

**Comment by vgskye** [comment]
what

**Comment by Madis0** [comment]
Minecraft usually stores its instance files on `.minecraft`. 

The default assumption is that this folder exists on `%appdata%\.minecraft` or `~/Library/Application Support/minecraft` or  `~/.minecraft`, but it may not always be the case (e.g. external drive). So, just like the launcher itself, and installers like Fabric's, this installer should have an option to let the user change its path. 

Once changed, the folder should be used for both isolated and non-isolated installations of FO, where isolated should be a subfolder and non-isolated the folder itself.

**Comment by vgskye** [comment]
sorry for not doing anything for a while; was busy with other stuff
I still can't find the option to change the instance folder on the launcher; the screenshot you sent only applies to the individual profile

**Comment by Madis0** [comment]
> I still can't find the option to change the instance folder on the launcher; the screenshot you sent only applies to the individual profile

Yes, but there is no need for that option _in the launcher_. Just keep the path stored in a config file (or similar) for the installer and use that path for every instance installed to the launcher. Or, more accurately, _every new instance_, there is no need to change older instances if the installer path changes.

**Comment by vgskye** [comment]
so, an option to have the profile folder in a place other than `.minecraft` or `.minecraft/fabulously-optimized-${mc_version}`?

**Comment by Madis0** [comment]
One folder path option for `~/.minecraft` part and one checkbox to choose whether to have subfolders by instance or use just the root of the .minecraft path.

**Comment by vgskye** [comment]
github apparently doesn't like me trying to close two issues with one commit
