### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer-rust#34]
Some users have requested a language switcher menu, besides the OS language detection. Not sure how easy it would be to do and therefore how high would it be in priority.

**Comment by vgskye** [comment]
This is possible, but it'll require thinking about UI design more cause I'm not sure how to fit a select-box in the current UI design

**Comment by Madis0** [comment]
Similar to the website perhaps? Whether you want to implement "Help us translate" is up to you.
![pilt](https://github.com/Fabulously-Optimized/vanilla-installer-rust/assets/8611110/41cbc5d2-b705-4e1f-bb0e-40585c84e89a)
