### ISSUE TITLE
Make downgrade warnings more detailed

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer-rust#9]
...and detect when the warning is not needed, aka empty folders as described below
https://github.com/Fabulously-Optimized/vanilla-installer-python/issues/80

**Comment by vgskye** [comment]
I can do the part described in the title. Just copy the message from python version?
Detecting frivolous warnings however, that's somewhat more involved, as frontend purposefully lacks any direct access to filesystem. Maybe just direct the user to remove paigaldaja_meta.json after moving the folders?

**Comment by Madis0** [comment]
> as frontend purposefully lacks any direct access to filesystem

Then a backend check is needed I believe? Without a check I don't see how would it even differ between overwriting .minecraft and having the isolated folder...

> Maybe just direct the user to remove paigaldaja_meta.json after moving the folders?

What does that file even do?

**Comment by vgskye** [comment]
paigaldaja_meta.json contains a list of files installed by the installer and whatever metadata frontend provides; frontend reads back the metadata to check if it is a downgrade. If you remove the file, the installer behaves as if it was a fresh install.

**Comment by Madis0** [comment]
Okay, then it could be mentioned in the instructions indeed.
